Local dev env improvements: usage guardrails & ES config

diff --git a/bin/local/env b/bin/local/env
--- a/bin/local/env
+++ b/bin/local/env
@@ -7,6 +7,14 @@ echo
 echo 'Setup environment ⚙️'
 echo
 
+if [ -z "${BASH_ARGV:-}" ]
+  then
+  echo 'Error: this script must be invoked via `source`:'
+  echo "  source $0"
+  echo
+  exit 1
+fi
+
 BUILD_DIR="$(pwd)"
 # The buildpack dir is two directories up from this script.
 # Using `BASH_ARGS` here because this script is meant to be called
@@ -21,6 +29,9 @@ if [ -f "$BUILD_DIR/.env" ]
     eval "export $LINE"
   done
 fi
+
+echo '       Parsing PIO_ELASTICSEARCH_URL'
+source "$BP_DIR/.profile.d/pio-elasticsearch.sh"
 
 echo '       Parsing DATABASE_URL'
 source "$BP_DIR/.profile.d/pio-postgres.sh"
